"""
version.py - Update version.h with current date/time and incremented revision.

Run by post.bat before each build.
  - VERSION      = today's date (YYYY-MM-DD)
  - VERSION_TIME = current time (HH:MM)
  - REVISION     = incremented by 1 each build
"""

import re
import datetime
import os

VERSION_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "version.h")

def read_version():
    """Read current revision from version.h, return 0 if not found."""
    revision = 0
    if os.path.exists(VERSION_FILE):
        with open(VERSION_FILE, "r") as f:
            content = f.read()
        m = re.search(r'#define\s+REVISION\s+(\d+)', content)
        if m:
            revision = int(m.group(1))
    return revision

def write_version(now, revision):
    """Write version.h with updated values."""
    content = (
        '/* version.h - Auto-generated by version.py, do not edit manually */\n'
        '#ifndef VERSION_H\n'
        '#define VERSION_H\n'
        '\n'
        '#define ROBOT_NAME     "PAO Robot"\n'
        '#define VERSION        "{date}"\n'
        '#define VERSION_TIME   "{time}"\n'
        '#define VERSION_YEAR   {year}\n'
        '#define VERSION_MONTH  {month}\n'
        '#define VERSION_DAY    {day}\n'
        '#define REVISION       {rev}\n'
        '\n'
        '#endif /* VERSION_H */\n'
    ).format(date=now.strftime("%Y-%m-%d"),
             time=now.strftime("%H:%M"),
             year=now.year, month=now.month, day=now.day,
             rev=revision)

    with open(VERSION_FILE, "w") as f:
        f.write(content)

def main():
    old_rev = read_version()
    new_rev = old_rev + 1
    now = datetime.datetime.now()

    write_version(now, new_rev)
    print("version.h: {} {} r{}  (was r{})".format(
        now.strftime("%Y-%m-%d"), now.strftime("%H:%M"), new_rev, old_rev))

if __name__ == "__main__":
    main()
